[package]
name = "jens"
description = "Readable templates for code generation"
license = "MIT/Apache-2.0"
version = "0.1.0"
authors = ["Jordan West <jordwest@gmail.com>"]
repository = "https://github.com/jordwest/jens"

[dependencies]
