[package]
name = "jens"
description = "Readable templates for code generation"
license = "MIT/Apache-2.0"
version = "0.1.0"
authors = ["Jordan West <jordwest@gmail.com>"]

[dependencies]
regex = "1.0.2"
